### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by remingtonCarmi** [phicau/IHFOAM#1]
Hi,
I tried to compile the allMake files but I get command error messages : 
./localMake: line 6: wclean: command not found
./localMake: line 8: wmake: command not found
Thanks for your help
RC

**Comment by AhmedUA** [comment]
Dear All, i am newbie in openfoam,despite many trials i am not able to figure out the problem.
I am having this same trouble but with olaFoam, as reported by remi below.
Please help me out with this, i just altered the basewaveflume blockMesh by moving its 2 right points closer to origin so that it makes a slope.and i am getting  floating point exception and simulation gets completed.
Please help me out anyone, i am freaking out


""Hi Pablo,

I am playing a little with IHFOAM but I encounter an error now.

I am just trying to modify the geometry of the base wave fume by changing the slope.

First I did a constant slope and everything worked just fine (simple I change the extremes right nodes of the tutorial).

Now I am trying to add a slope starting from the position 8.0 and going up to 1.0 m. So I have two hexagone.

The blockMesh seems to compile correctly and the initial data looks fine, but the code does not run.

Is there something I am missing?

This is my output

dhcp-96-243:baseWaveFlume3 Carmi$ ./runCase
blockMesh meshing...
Preparing 0 folder...
Setting the fields...
Running...
./runCase: line 16: 19453 Floating point exception: 8 ihFoam > ihFoam.log
Simulation complete.

Thanks

Remi""

**Comment by phicau** [comment]
Hi Ahmed,

this is a bug report system, not a support forum. cfd-online is the support forum that you are looking for to post your question.

As for your question, it is certainly an issue with the mesh, try checkMesh and see other examples online on how to create slopes properly.

Best,

Pablo

**Comment by AhmedUA** [comment]
@phicau,
Thankyou for your prompt reply, my apologies for asking it here in the first place it was mere confusion which made me type in query here. 
I tried checkMesh but it shows no errors though. I guess i will post all the detail of my issue in the forum then a/c to the posting criteria. 
Thankyou btw.

BR
Ahmed

**Comment by phicau** [comment]
Looking forward to answering your question at cfd-online once you provide more info.
